import React from "react";
import { Button } from "../Form/Button";
import Title from "../Layout/Title";
import { Link, useNavigate } from "react-router-dom";

function Modal({ ...props }) {
    return (
        <div className="fixed w-full h-full bg-black bg-opacity-50 z-20 layer">
            <div className="relative max-w-[530px] min-w-[400px] m-auto modalWrap">
                <button
                    onClick={props.onClick}
                    className="absolute top-[-40px] right-[0px]"
                >
                    <img
                        src={`${process.env.PUBLIC_URL}/images/btnModalClose.svg`}
                    />
                </button>
                {props.viewlistData[props.modalNum]}
            </div>
        </div>
    );
}
function MapModal({onClick, ...props }) {
    return (
        <div
            className="m-auto bg-white min-h-[100px] rounded-[1.25em] p-[30px]"
            {...props}
        >
            <div className="mb-3">
                <div className="flex justify-between gap-5 mb-3">
                    <div className="w-full bg-[#545454] text-white rounded-full py-1 text-center text-[0.875em]">
                        광역시도
                    </div>
                    <div className="w-full bg-[#545454] text-white rounded-full py-1 text-center text-[0.875em]">
                        시구군
                    </div>
                </div>
                <div className="flex justify-between gap-5">
                    <ul className="flex-auto localButton max-h-[400px] overflow-y-auto scrollWrap">
                        <li>
                            <label>
                                <input
                                    type="radio"
                                    name="radio1"
                                    id="#check_type1"
                                    className="active"
                                    checked
                                />
                                <span>서울특별시</span>
                            </label>
                        </li>
                        <li>
                            <label>
                                <input
                                    type="radio"
                                    name="radio1"
                                    id="#check_type1"
                                />
                                <span>강원도</span>
                            </label>
                        </li>
                        <li>
                            <label>
                                <input
                                    type="radio"
                                    name="radio1"
                                    id="#check_type1"
                                />
                                <span>경기도</span>
                            </label>
                        </li>
                        <li>
                            <label>
                                <input
                                    type="radio"
                                    name="radio1"
                                    id="#check_type1"
                                />
                                <span>경상남도</span>
                            </label>
                        </li>
                        <li>
                            <label>
                                <input
                                    type="radio"
                                    name="radio1"
                                    id="#check_type1"
                                />
                                <span>경상북도</span>
                            </label>
                        </li>
                        <li>
                            <label>
                                <input
                                    type="radio"
                                    name="radio1"
                                    id="#check_type1"
                                />
                                <span>광주광역시</span>
                            </label>
                        </li>
                        <li>
                            <label>
                                <input
                                    type="radio"
                                    name="radio1"
                                    id="#check_type1"
                                />
                                <span>대구광역시</span>
                            </label>
                        </li>
                        <li>
                            <label>
                                <input
                                    type="radio"
                                    name="radio1"
                                    id="#check_type1"
                                />
                                <span>대전광역시</span>
                            </label>
                        </li>
                        <li>
                            <label>
                                <input
                                    type="radio"
                                    name="radio1"
                                    id="#check_type1"
                                />
                                <span>부산광역시</span>
                            </label>
                        </li>
                        <li>
                            <label>
                                <input
                                    type="radio"
                                    name="radio1"
                                    id="#check_type1"
                                />
                                <span>세종특별자치시</span>
                            </label>
                        </li>
                        <li>
                            <label>
                                <input
                                    type="radio"
                                    name="radio1"
                                    id="#check_type1"
                                />
                                <span>울산광역시</span>
                            </label>
                        </li>
                        <li>
                            <label>
                                <input
                                    type="radio"
                                    name="radio1"
                                    id="#check_type1"
                                />
                                <span>전라남도</span>
                            </label>
                        </li>
                        <li>
                            <label>
                                <input
                                    type="radio"
                                    name="radio1"
                                    id="#check_type1"
                                />
                                <span>전라북도</span>
                            </label>
                        </li>
                        <li>
                            <label>
                                <input
                                    type="radio"
                                    name="radio1"
                                    id="#check_type1"
                                />
                                <span>제주</span>
                            </label>
                        </li>
                        <li>
                            <label>
                                <input
                                    type="radio"
                                    name="radio1"
                                    id="#check_type1"
                                />
                                <span>충청남도</span>
                            </label>
                        </li>
                        <li>
                            <label>
                                <input
                                    type="radio"
                                    name="radio1"
                                    id="#check_type1"
                                />
                                <span>충청북도</span>
                            </label>
                        </li>
                    </ul>
                    <div className="w-[1px] bg-slate-400"></div>
                    <ul className="flex-auto localButton max-h-[400px] overflow-y-auto scrollWrap">
                        <li>
                            <label>
                                <input
                                    type="radio"
                                    name="radio2"
                                    id="#check_type1"
                                />
                                <span>강남구</span>
                            </label>
                        </li>
                        <li>
                            <label>
                                <input
                                    type="radio"
                                    name="radio2"
                                    id="#check_type1"
                                />
                                <span>강동구</span>
                            </label>
                        </li>
                        <li>
                            <label>
                                <input
                                    type="radio"
                                    name="radio2"
                                    id="#check_type1"
                                />
                                <span>강북구</span>
                            </label>
                        </li>
                        <li>
                            <label>
                                <input
                                    type="radio"
                                    name="radio2"
                                    id="#check_type1"
                                />
                                <span>관악구</span>
                            </label>
                        </li>
                        <li>
                            <label>
                                <input
                                    type="radio"
                                    name="radio2"
                                    id="#check_type1"
                                />
                                <span>광진구</span>
                            </label>
                        </li>
                        <li>
                            <label>
                                <input
                                    type="radio"
                                    name="radio2"
                                    id="#check_type1"
                                />
                                <span>구로구</span>
                            </label>
                        </li>
                        <li>
                            <label>
                                <input
                                    type="radio"
                                    name="radio2"
                                    id="#check_type1"
                                />
                                <span>금천구</span>
                            </label>
                        </li>
                        <li>
                            <label>
                                <input
                                    type="radio"
                                    name="radio2"
                                    id="#check_type1"
                                />
                                <span>노원구</span>
                            </label>
                        </li>
                        <li>
                            <label>
                                <input
                                    type="radio"
                                    name="radio2"
                                    id="#check_type1"
                                />
                                <span>도봉구</span>
                            </label>
                        </li>
                        <li>
                            <label>
                                <input
                                    type="radio"
                                    name="radio2"
                                    id="#check_type1"
                                />
                                <span>동대문구</span>
                            </label>
                        </li>
                        <li>
                            <label>
                                <input
                                    type="radio"
                                    name="radio2"
                                    id="#check_type1"
                                />
                                <span>동작구</span>
                            </label>
                        </li>
                        <li>
                            <label>
                                <input
                                    type="radio"
                                    name="radio2"
                                    id="#check_type1"
                                />
                                <span>마포구</span>
                            </label>
                        </li>
                    </ul>
                </div>
            </div>
            <Button basicButton={true} ><Link to={'/mate/lover'} onClick={props.onClick}>확인</Link></Button>
        </div>
    );
}
function MapModalSelect({ onClick, ...props }) {
    return (
        <div
            className="m-auto bg-primary min-h-[100px] rounded-[1.25em] p-[30px]"
            {...props}
        >
            <div className="mb-3"><Link onClick={() => {
                    props.modalOpen(1);
                }}><img src={`${process.env.PUBLIC_URL}/images/mapSelect.png`} /></Link></div>
        </div>
    );
}
export { Modal, MapModal, MapModalSelect };

